### ISSUE TITLE
Removing Warnings: Supported source version 'RELEASE_8'

### ISSUE THREAD

**Issue by kevinshale** [c0stra/fluent-api-generator#5]
Would it be possible to remove the annotation [@SupportedSourceVersion(SourceVersion.RELEASE_8)](https://github.com/c0stra/fluent-api-generator/blob/1bd6b596051ca126994fed6b314a1e779f827280/fluent-api-generator/src/main/java/fluent/api/generator/processor/GeneratingProcessor.java#L68)?

I am getting these warnings at startup:

_Supported source version 'RELEASE_8' from annotation processor 'fluent.api.generator.processor.GeneratingProcessor' less than -source '11'_

**Comment by c0stra** [comment]
Sure. Let me have a look. In older versions I believe without this annotation it just gave different warning. So let me find best solution. Maybe adding newer versions as supported would be better.

**Comment by c0stra** [comment]
Yep. Without the annotation I'm getting these warnings:
```
java: No SupportedSourceVersion annotation found on fluent.api.generator.processor.GeneratingProcessor, returning RELEASE_6.
java: Supported source version 'RELEASE_6' from annotation processor 'fluent.api.generator.processor.GeneratingProcessor' less than -source '8'
```

**Comment by c0stra** [comment]
I use solution based on this info: https://stackoverflow.com/questions/8185331/forward-compatible-java-6-annotation-processor-and-supportedsourceversion

**Comment by c0stra** [comment]
Change released. Check version 2.18, once propagated to the public repo.
